apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipapp-sec
  namespace: secured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipapp
  template:
    metadata:
      labels:
        app: zipapp
    spec:
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: zipapp
        image: docker.io/library/zipapp:secure
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
