
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tracee
  namespace: tracee
spec:
  selector:
    matchLabels:
      app: tracee
  template:
    metadata:
      labels:
        app: tracee
    spec:
      hostPID: true
      containers:
        - name: tracee
          image: aquasec/tracee:latest
          securityContext:
            privileged: true
          env:
            - name: TRACE_OUTPUT_FORMAT
              value: json
            - name: TRACE_SECURITY_ALERTS
              value: "true"
          volumeMounts:
            - name: tracee-ebpf
              mountPath: /tmp/tracee
            - name: bpf
              mountPath: /sys/kernel/debug
            - name: modules
              mountPath: /lib/modules
            - name: usr-src
              mountPath: /usr/src
      volumes:
        - name: tracee-ebpf
          emptyDir: {}
        - name: bpf
          hostPath:
            path: /sys/kernel/debug
        - name: modules
          hostPath:
            path: /lib/modules
        - name: usr-src
          hostPath:
            path: /usr/src
