apiVersion: v1
kind: Service
metadata:
  name: falcosidekick
  labels:
    app: falcosidekick
spec:
  selector:
    app: falcosidekick
  ports:
    - port: 2801
      targetPort: 2801
      protocol: TCP
