apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-handler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-deployment-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-handler-deployment-binding
subjects:
  - kind: ServiceAccount
    name: falco-handler
    namespace: default
roleRef:
  kind: ClusterRole
  name: falco-deployment-manager
  apiGroup: rbac.authorization.k8s.io
