
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-custom-rules
  namespace: default
data:
  custom_rules.yaml: |
    - rule: Reverse Shell Detected
      desc: A reverse shell attempt detected in a container
      condition: >
        spawned_process and
        container and
        (proc.name = bash or proc.name = sh) and
        fd.name startswith "/dev/tcp/"
      output: >
        Reverse shell detected (user=%user.name command=%proc.cmdline container=%container.name)
      priority: CRITICAL
      tags: [network, mitre_execution]
