apiVersion: v1
kind: ServiceAccount
metadata:
  name: handler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-labeler
  namespace: default
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "patch", "label"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: handler-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: handler
    namespace: default
roleRef:
  kind: Role
  name: deployment-labeler
  apiGroup: rbac.authorization.k8s.io
